using System.Text;

namespace Assets.Discourse
{
    /// <summary>
    /// Represents a partially generated speech
    /// </summary>
    public class Discourse
    {
        private readonly StringBuilder text = new StringBuilder();

        /// <summary>
        /// Add more text to the discourse
        /// </summary>
        /// <param name="inc">Text to add</param>
        public void AddIncrement(string inc)
        {
            text.Append(inc);
        }

        /// <summary>
        /// Text generated by the discourse so far
        /// </summary>
        public string Text => text.ToString();
    }
}
